python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-0 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-1251 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-2502 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-3753 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-5004 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-6255 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-7506 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-8757 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-10008 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-11259 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-12510 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-13761 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-15012 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-16263 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-17514 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-18765 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-20016 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-21267 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-22518 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-23769 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-25020 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-26271 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-27522 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-28773 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-30024 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-31275 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-32526 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-33777 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-35028 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-36279 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-37530 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-38781 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-40032 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-41283 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-42534 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-43785 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-45036 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-46287 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-47538 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-48789 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-50040 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-51291 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-52542 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-53793 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-55044 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-56295 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-57546 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-58797 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-60048 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-61299 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-62550 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-63801 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-65052 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-66303 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-67554 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-68805 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-70056 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-71307 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-72558 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-73809 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-75060 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-76311 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-77562 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-78813 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-80064 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-81315 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-82566 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-83817 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-85068 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-86319 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-87570 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-88821 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-90072 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-91323 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-92574 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-93825 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-95076 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-96327 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-97578 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-98829 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-100080 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-101331 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-102582 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-103833 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-105084 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-106335 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-107586 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-108837 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-110088 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-111339 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
python ckpt_sparsity.py --checkpoint=/scratch/hj14/tpu_checkpoints/ckpt-2/model.ckpt-112590 --sparsity_technique=magnitude_pruning --model=rn50 | tee -a sparsity-ckpt.csv 
